#!/bin/bash

# Setting up the inmanta working environment
source /usr/bin/inmanta-with-env

# SHELL COLOR MANAGEMENT
# ----------------------
# This section only allows to manage the CLI color outputs for better messages,
# should not be changed since these are defaults.

end="\033[0m"

function redb {
    redb="\033[1;31m"
    echo -e "${redb}${1}${end}"
}

function greenb {
    greenb="\033[1;32m"
    echo -e "${greenb}${1}${end}"
}

function yellow {
    yellow="\033[0;33m"
    echo -e "${yellow}${1}${end}"
}

function lightblueb {
    lightblueb="\033[1;36m"
    echo -e "${lightblueb}${1}${end}"
}

# HELPER METHODS
# --------------
# This section contains methods that can be used for the different commands
# supported by this file

# The method prints a short usage message for the container image.
show_header()
{
    echo '';
    echo 'Usage: [command] [options...]'
    echo '                                                         ';
    greenb ' Entrypoint for the inmanta orchestrator container.';
    echo '';
    lightblueb ' You can use any of the helper commands below to start the server easily.';
    lightblueb ' If you want to use a custom command, you can as well, it will be handed';
    lightblueb ' over to exec.';
    echo '';
    echo 'Commands:'
    echo -e '  server          \t Start the inmanta server using in place configs'
    echo -e '  server-with-ssh \t Start the inmanta server and the ssh daemon'
    echo -e '  help            \t Show this help message'
    echo '';
    echo 'Options:'
    echo -e '  --wait-for-host <host> \t Host that has a port we want to wait for'
    echo -e '                         \t (--wait-for-port should be provided as well)'
    echo -e '  --wait-for-port <port> \t Port on the host we are waiting for'
    echo -e '                         \t (--wait-for-host should be provided as well)'
    echo -e '  --wait-for <seconds>   \t Amount of seconds to wait for the port'
    echo -e '                         \t (optional, default: 30)'
    echo '';
}

# This methods configures the ssh deamon, and creates new ssh keys
configure_ssh()
{
    sudo sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd
	sudo ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -N ''
	sudo ssh-keygen -t dsa -f /etc/ssh/ssh_host_dsa_key -N ''
}

# This methods ensures that the current user has the correct permissions set
# on its ssh folder, which might not be the case when some files are mounted
# in there during the container creation.
enforce_ssh_perms()
{
    sudo chown $USER:$USER $HOME/.ssh --recursive
    chmod 600 $HOME/.ssh --recursive
}

# Wait for at most X seconds for the database to be reachable
wait_for_host_port()
{
    host=$1
    port=$2
    max_attempts=$3

    if [ "$host" == "0" ] || [ "$port" == "0" ]; then
        # No config provided to wait for the host
        return
    fi

    yellow "Will wait at most $max_attempts seconds for $host:$port to become reachable"

    count=0
    until nc -z -v -w30 "$host" "$port" || [ $count -ge $max_attempts ]
    do
        sleep 1
        count=$(( $count+1 ))
    done

    if [ $count -ge $max_attempts ]; then
        redb "$host:$port is still unreachable after $max_attempts, stopping now." >& 2
        exit 1
    fi
}

# MAIN SECTION
# ------------
# Start checking arguments and act accordingly

# Checking if the entrypoint received any argument at all
if [ $# -eq 0 ]; then
    redb 'No command provided, container can not start.' >& 2
    show_header
    exit 1
fi

# Checking command options
wait_for_host=0
wait_for_port=0
wait_for=30

load_options()
{
    while :; do
        case $2 in
            --wait-for-host)
                wait_for_host="$3"
                shift
                ;;
            --wait-for-port)
                wait_for_port="$3"
                shift
                ;;
            --wait-for)
                wait_for="$3"
                shift
                ;;
            --)
                shift
                break
                ;;
            -?*)
                redb "Unknown option (ignored): $2"
                show_header
                exit 1
                ;;
            *)
                break
        esac
        shift
    done
}

# Checking if the first argument is a command we know
# Otherwise we default to the base image entrypoint
case $1 in

    'server')

        load_options "$@"

        # Wait at most 30 seconds for the database to be reachable
        wait_for_host_port $wait_for_host $wait_for_port $wait_for

        # Start the server only
        /usr/bin/inmanta -vvv --timed-logs server
        ;;

    'server-with-ssh')

        load_options "$@"

        # Start the server with an ssh deamon
        configure_ssh
        enforce_ssh_perms
        sudo /usr/sbin/sshd -D > /var/log/sshd.log &

        # Wait at most 30 seconds for the database to be reachable
        wait_for_host_port $wait_for_host $wait_for_port $wait_for

        # Start the server
        /usr/bin/inmanta -vvv --timed-logs server
        ;;

    'help')

        # Show the help message
        show_header
        ;;

    *)
        # Simply exec the command
        exec "$@"
        ;;

esac
